FROM python:3.7

# copy the local requirements.txt file to the
# /app/requirements.txt in the container
# (the /app dir will be created)
COPY ./requirements.txt /app/requirements.txt

# install the packages from the requirements.txt file in the container
RUN pip install -r /app/requirements.txt

# expose the port that uvicorn will run the app
EXPOSE 8000

# copy the local app/ folder to the /app fodler in the container
COPY ./apiV2 /app

# set the working directory in the container to be the /app
WORKDIR /app

# execute the command python app.py (in the WORKDIR) to start the app
CMD ["python", "app.py"]
